
import LegalPageLayout from '@/components/layout/LegalPageLayout';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <LegalPageLayout pageTitle="Terms of Service">
      <section className="space-y-6">
        <h2 className="text-2xl font-semibold text-foreground">1. Acceptance of Terms</h2>
        <p>
          By accessing and using PromptForge (the "Service"), you accept and agree to be bound by the terms and
          provision of this agreement. In addition, when using these particular services, you shall be subject to
          any posted guidelines or rules applicable to such services. Any participation in this service will
          constitute acceptance of this agreement. If you do not agree to abide by the above, please do not use
          this service.
        </p>

        <h2 className="text-2xl font-semibold text-foreground">2. Service Description</h2>
        <p>
          PromptForge is an AI-powered application prototyping tool that assists users in generating application
          ideas, detailed proposals, market analysis, feature prioritization, pricing strategies, and developer prompts.
          The Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind.
        </p>

        <h2 className="text-2xl font-semibold text-foreground">3. User Accounts</h2>
        <p>
          To access certain features of the Service, you may be required to create an account. You are responsible
          for maintaining the confidentiality of your account information and for all activities that occur under
          your account. You agree to notify us immediately of any unauthorized use of your account.
        </p>
        
        <h2 className="text-2xl font-semibold text-foreground">4. User Conduct</h2>
        <p>
          You agree not to use the Service for any unlawful purpose or in any way that interrupts, damages, or impairs
          the service. You agree not to transmit any material that is defamatory, offensive, or otherwise objectionable.
        </p>

        <h2 className="text-2xl font-semibold text-foreground">5. Intellectual Property</h2>
        <p>
          The Service and its original content, features, and functionality are and will remain the exclusive
          property of PromptForge and its licensors. Content generated by you using the Service remains your
          intellectual property, subject to the rights necessary for us to provide and improve the Service.
        </p>
        
        <h2 className="text-2xl font-semibold text-foreground">6. Subscription and Payment</h2>
         <p>
          Certain features of the Service may be available only through a paid subscription ("Premium Plan").
          Details regarding subscription fees, billing cycles, and cancellation policies are available on our Pricing page.
          All payments are processed through a third-party payment processor.
        </p>
        
        <h2 className="text-2xl font-semibold text-foreground">7. Limitation of Liability</h2>
        <p>
          In no event shall PromptForge, nor its directors, employees, partners, agents, suppliers, or affiliates,
          be liable for any indirect, incidental, special, consequential or punitive damages, including without
          limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your
          access to or use of or inability to access or use the Service.
        </p>

        <h2 className="text-2xl font-semibold text-foreground">8. Changes to Terms</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision
          is material we will provide at least 30 days' notice prior to any new terms taking effect. What
          constitutes a material change will be determined at our sole discretion.
        </p>

        <h2 className="text-2xl font-semibold text-foreground">9. Governing Law</h2>
        <p>
          These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction/Country],
          without regard to its conflict of law provisions.
        </p>

        <h2 className="text-2xl font-semibold text-foreground">10. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us via our <Link href="/contact" className="text-primary hover:underline">Contact Page</Link>.
        </p>
        <p className="text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
      </section>
    </LegalPageLayout>
  );
}

